### ISSUE TITLE
nakodovovat case Study XIXOIO

### ISSUE THREAD

**Issue by leomira** [topmonks/topmonks-webs#109]
Podklad: https://topmonks.quip.com/lmluAPDSccY0/Case-Study-Xixoio
Dalsie info moze poskytnut @Masa331 ci Josef Tetek.
[ x] Navrhnut vizual podla stylu Blockchain Webu
[ x] Upravit (skratit) text do citatelsky privetivej podoby
[ x] Ilustrovat (minimalne cast s timeline, possibly aj viac)

**Comment by leomira** [comment]
ready na implementaciu: https://www.figma.com/file/fR0P8iIOB3cXsIkj1tbHxEyc/xixoio-case-study---verze2
mobilna verzia = cestou najmensieho odporu, info pls @trnkapavel .

**Comment by Cihlova** [comment]
DONE, now: fighting with details.
