### ISSUE TITLE
Hookamonk Formulář

### ISSUE THREAD

**Issue by Cihlova** [topmonks/topmonks-webs#1169]
1. Napojit formulář na naše AWS
2. Jakmile někdo submitne formulář, tak mu přijde email

**Comment by Cihlova** [comment]
@trnkapavel mohl bys prosím upřesnit, jak třeba ten email má vypadat a další detaily pro Vaška okolo toho formuláře?

**Comment by trnkapavel** [comment]
Text e-mailu:

Congrats, you’re one step closer to your Warp experience!

Hi xxx,

Thanks for getting in touch with us, your request for Warp at home / Warp at work / Warp for lounge has been well received and we will get back to you as soon as possible.

Thanks and regards,

Hookamonk team

**Comment by trnkapavel** [comment]
Obsah se bude odesílat na email klienta uvedený ve formuláři. Na mailto:sales@hookamonk.com bude chodit požadavek s objednávkou. ![image](https://user-images.githubusercontent.com/11630865/139875821-976f50df-bbf7-4d44-a867-33987e3be68f.jpeg)
