### ISSUE TITLE
Vytvořit monkstage web

### ISSUE THREAD

**Issue by vercat** [topmonks/topmonks-webs#128]
@paulus-tom 
- [x] wireframe
- [x] brand
- [x] design webu - ilustrace do headeru, video play button, ilustrace za fotky
- [x] touchpointy (bannery, rollup - včetně ilustrace, ...)

@vaclav-slavik
- [x] web dev
- [x] com doména
- [x] com doména má dvě jazykové verze, vždy online jen jedna z nich

@vercat  
- [x] texty

**Comment by vercat** [comment]
startup stage/ monkstage návrh webu
https://www.figma.com/file/PEOEcIWHRlJcH0CTtpZcRbig/Startup-Stage-%5Bweb%5D

**Comment by vercat** [comment]
@vaclav-slavik 
Texty budu mít nejpozději do příští středy hotové. Pošlu ti potom přímo sem odkaz na quip.

**Comment by rarous** [comment]
Moc nechápu, proč by měla být česká jazyková verze na com a ne na cz a pak vymýšlet nějakou obskurnost s přepínáním jazyků na com? Český obsah patří na cz doménu, anglický na com. Dá se pak přesměrování uživatelů podle preferencí jazyka řešit jednoduše a pomocí W3 standardů.

**Comment by vaclav-slavik** [comment]
@vercat pojďme dořešit to s těmi jazyky. Souhlasím s @rarous že je blbost mít český obsah na .com doméně. Od začátku bylo zamýšleno mít na tomponks.com anglické a na .cz české verze. Chyba byla v tom že se na poslední chvíli změnil jazyk pro monkstage blockchain edition. Pokud je tedy jasné že obsah bude vždy jen v češtině, tak bych to po proběhnutí nadcházející monkstage přesunul na .cz. Souhlas?

**Comment by vaclav-slavik** [comment]
@vercat jelikož už je jasné, že monkstage blockchain edition nebude, není teď správný čas vyřešit tu záležitost s doménou a přesunout to na topmonks.cz? Jsme si jistí, že budeme mít vždy český obsah? Rád bych se tohohle problému zbavil a označil tuhle kartu jako done...

**Comment by vercat** [comment]
@vaclav-slavik 
já určitě souhlasím s tím, že český obsah by měl být na cz doméně. Posledně se na poslední chvíli změnil obsah do češtiny. Ale situace je teď taková, že simona plánuje další stage (červnovou) nejspíš také v angličtině...

**Comment by vercat** [comment]
Ok. Stav je takový, že necháme monkstage na .com doméně, odbavíme červnovou monkstage, po ní bude hlavní doménou .cz, kde bude obsah. 
Doména .com se pak bude přesměrovávat vždy na .cz doménu.
Dohodnuto s @vaclav-slavik
