### ISSUE TITLE
Päta na webe Blockchain studia

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#143]
Ahoj,

viac ľudí mi dalo feedback, že by na stránke Blockchain studia očakávali rovnakú pätu ako na ostatných TM weboch. Dáva to zmysel.

Upravil som na nej farbu, aby to sedelo do dizajnu blockchain webu. Keď bude niekto mať čas, prosím prehoďte to.

Dizajn:
https://www.figma.com/file/POCJGJXlqCiapGxT4yUeBd/blockchain-web-topmonks?node-id=0%3A1

Díky

**Comment by Cihlova** [comment]
Done

**Comment by Cihlova** [comment]
done
