### ISSUE TITLE
Nový formulář

### ISSUE THREAD

**Issue by Simooonsk** [topmonks/topmonks-webs#146]
U toho nového formuláře na studio.topmonks.com, když ho odkliknu, mělo by na mě vyskočit info ve smyslu: "Děkujeme za Váš zájem. Formulář byl odeslán, budeme Vás do 48h kontaktovat."

**Comment by trnkapavel** [comment]
Ve Figme je pripraveny navrh https://www.figma.com/file/VidXK3GhxvqaBD0M1qV8AiTw/Startup-studio-desktop-mobile?node-id=0%3A1

**Comment by vaclav-slavik** [comment]
![image](https://user-images.githubusercontent.com/14313898/55240542-5ee21880-5239-11e9-8580-ced981b57185.png)

Na základně CE feedbacku jsem implementoval vymazání obahu formuláře při úspěšném odeslání mailu...
