### ISSUE TITLE
Iterácia Homepage TopMonks

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#157]
Ahoj,

so Simonou, Pavlem a Verčou sme ziterovali homepage TopMonks. Trošku sme to presvetlili, vyhodilo zbytočné texty a prihodili referencie.

Čo treba ešte dodať?

[] Dodať a preložiť referencie.

Dizajn nájdeš ako vždy [vo Figme ](https://www.figma.com/file/DbvniEPJdbB5OLUonqkgYWT6/TopMonks-web?node-id=11%3A437)

Máš tam aj 3 komentáre, stačí stlačiť C a uvidíš ich :)

Ak bude niečo chýbať alebo bude zle nakreslené, určite ma pingni.

Díky 💯

**Comment by rarous** [comment]
BTW proč je tam logo Spořky? pro tu už skoro rok nic neděláme

**Comment by paulus-tom** [comment]
Logá som bral z aktuálneho webu TM :) Za koho ju môžem vymeniť?

**Comment by rarous** [comment]
@paulus-tom vzpomínáš, jak jsi mi dělal loga do Insightu? :)

**Comment by rarous** [comment]
když už děláme lehký facelift, zkuste se zamyslet, jak ten začátek stránky zlepšit, aby tam nemusel být ten aktuální cirkus, kvůli kontrastům pro menu. Taky si nejsem jistej, jestli Fil chce být takhle exponovaný a jestli se chce prezentovat jako sektička Jiřího Fabiána. TopMonks není One Man Show. Chápu, s fotkama to není jednoduchý, ale přesto :)

**Comment by paulus-tom** [comment]
Ďakujem za feedback  ❤️

Fotku som tam mal pôvodne túto Leinu otočenú zrkadlovo, akurát nemáme ešte práva na tú fotku z Cocumy 🤷‍♂️🤦‍♂️
![image](https://user-images.githubusercontent.com/39488664/52632566-389f2e00-2ec2-11e9-8273-cfb28800925d.png)

Tú Filovi fotku zatiaľ dodala Simona a v podstate sedí aj farbami (oranžová, fialová) do brandu. Prehodíme ju neskôr za niečo iné, ak nájdeme niečo lepšie. 

Nad menu sa ešte zamyslím, bolo by fajn to zjednotiť na celom webe :)

**Comment by paulus-tom** [comment]
@ciihla vo Figme som vymenil obrázky, ktoré by tam na teraz mohli byť. 

Upravil som aj navbar, viď úplne prvý screen, resp. aj ostatné screeny na webe. Proste tam šupneme biely background, tmavý text a fialové logo.

Sticky môže ostať ako je, len zmeň prosím farbu písma na #3C3C3B a pri hover efekte tam hoď #FE664B a underline :)

Díky! <3

**Comment by ciihla** [comment]
@paulus-tom Proc jsi tagnul me? Asi jsi chtel nekoho jineho? ;-)

**Comment by paulus-tom** [comment]
Shit sorry. Príliš veľa stavebného materiálu :D @Cihlova

**Comment by ciihla** [comment]
Cihla jako cihla :) Akorat s Anickou budes mit vice uspechu ;-)

**Comment by Cihlova** [comment]
:D

**Comment by rarous** [comment]
@paulus-tom chybí mi návrh pro mobily a případně tablety

**Comment by paulus-tom** [comment]
Pokúsim sa urobiť dnes.

Dňa st 13. 3. 2019 o 6:26 Aleš Roubíček <notifications@github.com>
napísala(a):

**Comment by Cihlova** [comment]
Vypuštěná TopMonks HP EN version. @vaclav-slavik  dodá main obrázek zítra a @rarous  poladí trychtýř. <3

**Comment by vaclav-slavik** [comment]
Doladil jsem loga partnerů (nyní v svg) a úvodní fotku dle Figmy.

**Comment by vaclav-slavik** [comment]
"Trychtýřová" sekce na .com a .cz webu hotová (včetně responzivního chování). cc @paulus-tom

**Comment by paulus-tom** [comment]
❤️

Dňa št 28. 3. 2019 o 15:09 Václav Slavík <notifications@github.com>
napísala(a):
