### ISSUE TITLE
Dokoncit poslednu referenciu pre blockchainweb

### ISSUE THREAD

**Issue by leomira** [topmonks/topmonks-webs#159]
TEXT:
> Lumir has proven to be an incredibly valuable team player that matched very well with our senior >product/dev team and proved exceptionally fast and innovative thinker in designing and auditing our >smart contracts architecture.
Logo mam zatial len na tejto stranke: https://www.debnk.io/
Zakaznik je DEBNK
Menovite Patrik Tjokorda, CEO

**Comment by leomira** [comment]
![img-20190214-wa0000](https://user-images.githubusercontent.com/25779015/52786539-64a1e700-305b-11e9-86a7-f65a94e4876f.jpg)
@paulus-tom tu je logicko

**Comment by paulus-tom** [comment]
Za mňa done. @Cihlova Pozrieš na to? 💯

https://www.figma.com/file/POCJGJXlqCiapGxT4yUeBd/blockchain-web-topmonks?node-id=0%3A1

**Comment by leomira** [comment]
@Cihlova urobila som malinku upravu v texte u referencie Nataliye Rozhok - pridala som tam jej poziciu. prosim uprav pak i na webiku.

**Comment by Cihlova** [comment]
done
