### ISSUE TITLE
Firemní kultura na About us

### ISSUE THREAD

**Issue by rarous** [topmonks/topmonks-webs#16]
Na stránce About us, bychom se měli více pověnovat naší firemní kultuře, vytáhnout důležité aspekty jako je remote friendly prostředí, používání cloudových služeb (naťuknuté v sekci How We Work), osobní zodpovědnost, a další věci, co by mohly podpořit hiring.

**Comment by paulus-tom** [comment]
Túto issue môžeme zavrieť, odladili sme to v návrhoch nových /about-us a /jobs stránok.

**Comment by paulus-tom** [comment]
Close
