### ISSUE TITLE
Fotka na Jobs

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#165]
Ahoj,

sadli sme si s Aničkou k tomu nakódenému Jobs webíku a poprosil by som jednu malú zmenu. Odstránili sme prvý šedý background a pridali sme tam fotku. Nesúri to, ale bude fajn to tam mať.

Je to samozrejme pripravené vo Figme.

https://www.figma.com/file/DbvniEPJdbB5OLUonqkgYWT6/TopMonks-web?node-id=11%3A437

Díky, Tom

**Comment by Cihlova** [comment]
done
