### ISSUE TITLE
Team na stránce About Us

### ISSUE THREAD

**Issue by rarous** [topmonks/topmonks-webs#24]
Přidat sekci Team na stránku About Us.

Jednotlivé záznamy členů teamu budou samostatné MD soubory s metadaty a biem monka.

Fotky jednotlivých monků budeme brát ze Slacku pomocí URL v Insight. `https://insight.topmonks.com/avatar/{:slug}`, kde `{:slug}` je alias před `@topmonks.com` (většinou je to `jmeno-prijmeni`, ale existují některé výjimky jako `eliska`).

- [ ]  zobrazeni modal detailu pri kliknuti na clena

**Comment by paulus-tom** [comment]
@rarous asi môžeme closenúť, nie?
