### ISSUE TITLE
Monks Lab web

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#318]
[Neue Einstellung 105.zip](https://github.com/topmonks/topmonks-webs/files/3513150/Neue.Einstellung.105.zip)
Ahoj,

dal som dokopy dizajn webu pre Monks Lab. Texty a konkrétne ikony budeme ešte ladiť, kódiť sa to ale môže. 

Celý dizajn nájdeš vo [Figma projekte](https://www.figma.com/file/njxfl04I0t8DgCkxXUe2df/Web?node-id=9%3A2). Snažil som sa spoznámkovať aj linky a pod. 

Máme urobené [Repo na Monks Lab](https://github.com/topmonks/monkslab) kvôli Wikine, takže neviem, či nebude lepšie mať kód tam. 

Fonty sú v prílohe issue.

Hover efekty, prípadne ostatné veci máš vedľa prvého artboardu. 

Čo by som okrem dizajnu ešte potreboval?
- Aby sa akcie dali pridávať cez JSON rovnako ako na Kaféčkovom webe
- Aby bola mapa, ktorá je v dizajne klasická mapa v ktorej sa dá scrollovat
- Aby formulár posielal mail na hello@monkslab.cz (teď to riešil Vašek aj na Hookamonk webe)
- Aby to fičalo na Monkslab.cz (doména je kúpená na Czech hostingu)
- Aby sme mali maily (aspoň zatiaľ iba) tom@monkslab.cz a hello@monkslab.cz

Nijak extrémne to nespěchá. Verča sa k tomu dostane beztak až po dovolenke, takže minimálne týždeň času na to je. Mobilné verzie som nekreslil, pokiaľ nebude niečo jasné, doladíme to za behu.

Moc díky

Tom

**Comment by Cihlova** [comment]
Hotovo, až na ty JSON akce. Aleš by vytvořil plugin a to tam pak vložíme a dořešíme:)!

**Comment by paulus-tom** [comment]
Skvele :) Moc dík.

Mám ešte pár vecí - 
1. keď to Verča otextuje, pridáme jeden farebný boxík nad ohyb, kde bude info o otvorení
2. Akce niesú linky, v prototype je spravená interakcia a je to aj v "styleguide" na kraji boardov
3. Podstránky nemajú aktívnu položku v headeri
4. Položky v menu by mali mať border by default, ktorý je transparentný a na hover by sa mala pridať farba - tým pádom nebude menu skákať pri hover efekte

Inak skvelá práca ❤️

**Comment by paulus-tom** [comment]
+ pridávam favicon :) 
[favicon-monkslab.zip](https://github.com/topmonks/topmonks-webs/files/3560383/favicon-monkslab.zip)

**Comment by Cihlova** [comment]
1. Větička přidaná ☑
2. Akce hotovo - opacity 60% teda - je to ok? ☑
3. Podstránky aktivní položka - to už si asi urobil ty ☑
4. Ten text je pryč, takže ☑
5. Lol no jo :D Sorry! taky hotovka  ☑
6. Děkuji za favicony, přidány  ☑
