### ISSUE TITLE
Nová teamová stránka

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#321]
Ahoj,

dal som dokopy teamovú stránku. Prosím do menu pridať položku "Tým" a odstrániť "o nás"

Vizuál viď [Figma súbor](https://www.figma.com/file/DbvniEPJdbB5OLUonqkgYWT6/TopMonks-web?node-id=1617%3A2187).

Moc díky

Tom

**Comment by Cihlova** [comment]
Měla by být ready, ještě Aleš se asi podívá na ty členy, aby to sedělo a neopakovali se pak dole. Tím pádem bude pak sedět i pozadí.
