### ISSUE TITLE
Bezpečnostní audit

### ISSUE THREAD

**Issue by paulus-tom** [topmonks/topmonks-webs#333]
Ahoj,

s Jurrim sme dali dokopy stránku bezpečnostného auditu. [Vizuál a obsah nájdeš vo Figme](https://www.figma.com/file/DbvniEPJdbB5OLUonqkgYWT6/TopMonks-web?node-id=1691%3A34). Layout je na 90% zhodný s digitálnym auditom.

**Title stránky** - Bezpečnostní audit - TopMonks
**URL stránky** - /bezpecnosti-audit
**Ako sa tam dostanem?** - z karty _Chci poradit s bezpečností webu nebo aplikace_ na hlavnej stránke

Díky

Tom 🤟

**Comment by Cihlova** [comment]
DONE ☑:)
