### ISSUE TITLE
topmonks/contact update

### ISSUE THREAD

**Issue by jinjanko** [topmonks/topmonks-webs#59]
1. OFFICE - dat ten isty format ak maju ludia pod tym. takto to vyzera nejednotne, alebo radsej uplne zmazat

2. pridat dalsiu karticku:
**US SALES**
Berenika Alexandre:
+14155256313
berenika.alexandre@topmonks.com

2.5
jirkove meno oddelit od tel. cisla >>> ENTER - zjednotenie vyzoru

3. office presunieme na Berenikin coworking:
**San Francisco**
TopMonks INC
981 Mission St
San Francisco CA 94103
United States

+ presunul by som to na prve miesto
+ zmenit google map link

![topmonks contacts](https://user-images.githubusercontent.com/24315362/47082691-b8680500-d20e-11e8-8725-d0ae81f4d01a.png)

**Comment by paulus-tom** [comment]
Vyriešené v #92
