### ISSUE TITLE
Optimalizace CSS loadingu podle tipů v článku

### ISSUE THREAD

**Issue by rarous** [topmonks/topmonks-webs#88]
* [x] určitě bude potřeba hodit async scripty před načítání stylů https://csswizardry.com/2018/11/css-and-network-performance/
* [ ] rozsekat jednotlivé moduly do samostatných CSS souborů a načítat je progresivně v místě, před jejich použitím https://jakearchibald.com/2016/link-in-body/

**Comment by vaclav-slavik** [comment]
@rarous můžeme tohle po tvojí práci na rozdělení css stylů dle komponent prohlásit za done? :-)

**Comment by rarous** [comment]
ještě se to musí dodělat na CZ :) Provede Cihlička, už jsme domluvený

S pozdravem a přáním pěkného dne

Aleš Roubíček

-----
web: http://rarous.net/
+420 737 461 283
