### ISSUE TITLE
Upravit web programování pro děti TopMonks

### ISSUE THREAD

**Issue by Eliskaztopmonks** [topmonks/topmonks-webs#96]
Potřebovala bych upravit popisek u ikonky 4 týdny - přepsat popisný text na -4 setkání v měsíci
Odstranit sekci naši lektoři  a přepsat kontakt na Davida Zábrže- david.zabrz@topmonks.com + fotografie 
Do rozsah kurzu - detaily -přidat cenu  pouze 30 000 Kč
Deadline mame nejlepe do 4.12. Kdo na tom budete dělat, klidně mi napište :) nejsem si jistá zda je muj popis srozumitelý ..
MOC DĚKUJEME :) Eliška a David

**Comment by rarous** [comment]
Cena tam není schválně, kvůli nabídkám na míru. Vracet ji tam nebudeme.
@Eliskaztopmonks Dodej fotografii, co tam chceš dát.

**Comment by Cihlova** [comment]
Já na to můžu mrknout nějak v pátek. Jen mi pak teda dodej prosím ty fotky :)

**Comment by Eliskaztopmonks** [comment]
moc děkuji :) fotku jen jednu - ke kontaktu Davida  ( nejlepe ji vzít ze stránek our team ale případně pošlu na mail :)
